# Project Info
front.host=
spring.application.name=
server.port=
server.servlet.context-path=

# Admin member info
admin.password=
admin.settingPassword=

# devtools
spring.devtools.livereload.enabled=
spring.devtools.restart.enabled=

# Thymeleaf
spring.thymeleaf.mode=
spring.thymeleaf.cache=
spring.thymeleaf.prefix=
spring.thymeleaf.suffix=

spring.web.resources.chain.enabled=
spring.web.resources.add-mappings=
spring.web.resources.static-locations=

# DB Connection (log4jdbc)
spring.datasource.driver-class-name=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# Model Location
mybatis.type-aliases-package=
mybatis.config-location=
mybatis.mapper-locations=

##aws path
upload.path=

# MAPPER LOG PRINT MAPPER
logging.level.root=
logging.level.com.jabibim.admin.mybatis.mapper.AcademyMapper=
logging.level.com.jabibim.admin.mybatis.mapper.TeacherMapper=
logging.level.com.jabibim.admin.mybatis.mapper.ContentMapper=

#window path
my.savefolder=

# File Upload
spring.servlet.multipart.enabled=
spring.servlet.multipart.max-file-size=
spring.servlet.multipart.max-request-size=


# AWS S3
cloud.aws.s3.bucket=
cloud.aws.region.auto=
cloud.aws.region.static=
cloud.aws.stack.auto=
cloud.aws.credentials.access-key=
cloud.aws.credentials.secret-key=

#Redis
spring.data.redis.host=
spring.data.redis.port=
spring.data.redis.password=
spring.data.redis.ssl.enabled=
spring.data.redis.timeout=

google.client.id=
google.client.secret=
google.redirect.uri=
google.authorization.uri=
google.token.uri=

# ffmpeg
ffmpeg.location=
ffprobe.location=
ffmpeg.exe.location=
ffprobe.exe.location=
file.upload-raw-dir=
file.upload-encode-dir=

# slack webhook url
slack.webhook.url=

# websocket allow origin
websocket.allow-origin=
erver.forward-headers-strategy=